import Fastify from 'fastify'
import multipart from '@fastify/multipart'
import cors from '@fastify/cors'
import { randomUUID } from 'node:crypto'
import { config } from './config'
import { createJob, getJob } from './jobs'
import { storage, results } from './storage'
import { enqueue } from './queue'
export function buildApi(){ const app=Fastify({logger:true}); app.register(cors,{origin:process.env.WEB_ORIGIN??true}); app.register(multipart,{limits:{fileSize:config.maxBytes,files:1}}); app.get('/health',async()=>({status:'ok'})); app.get('/ready',async(_r,reply)=>{if(!process.env.REDIS_URL)return reply.code(503).send({status:'not_ready',reason:'REDIS_URL is not configured'}); return {status:'ready'}}); app.post('/api/v1/jobs',async(req,reply)=>{try{const file=await req.file(); if(!file)return reply.code(400).send({error:{code:'INVALID_FILE',message:'multipart field file is required'}}); const data=await file.toBuffer(); const magic=data.slice(0,12).toString('hex'); const allowed=['89504e470d0a1a0a','ffd8ff','52494646']; if(!allowed.some(x=>magic.startsWith(x)))return reply.code(415).send({error:{code:'UNSUPPORTED_FORMAT',message:'PNG, JPEG, and WebP are supported'}}); const key=`${randomUUID()}/input`; await storage.put(key,data); const job=createJob({originalFilename:file.filename,inputMimeType:file.mimetype,inputSizeBytes:data.length,inputStorageKey:key}); await enqueue(job.id,key); return reply.code(202).send({jobId:job.id,status:job.status})}catch(error){if((error as {code?:string}).code==='FST_INVALID_MULTIPART_CONTENT_TYPE') return reply.code(400).send({error:{code:'INVALID_FILE',message:'multipart field file is required'}}); req.log.error(error); return reply.code(503).send({error:{code:'QUEUE_ERROR',message:'Processing is temporarily unavailable'}})}}); app.get('/api/v1/jobs/:id',async(req,reply)=>{const job=getJob((req.params as {id:string}).id); if(!job)return reply.code(404).send({error:{code:'JOB_NOT_FOUND',message:'Job not found'}}); return {id:job.id,status:job.status,...job.status==='completed'?{result:{width:job.outputWidth,height:job.outputHeight,format:'png',downloadUrl:job.outputStorageKey&&results.url(job.outputStorageKey)}}:{},...(job.status==='failed'?{error:{code:job.errorCode,message:job.errorMessage}}:{})}}); app.get('/api/v1/files/result/:key',async(req,reply)=>{try{const key=decodeURIComponent((req.params as {key:string}).key); const data=await results.get(key); return reply.type('image/png').send(data)}catch{return reply.code(404).send({error:{code:'RESULT_NOT_FOUND',message:'Result not found'}})}}); return app }
