import type { Metadata } from "next"
import Link from "next/link"
import { ArrowRight, Check } from "lucide-react"
import { SiteHeader } from "@/components/site-header"
import { ProductFooter } from "@/components/product-footer"
export const metadata: Metadata = { title: "Pricing — CutoutBG", description: "Explore the future CutoutBG plans." }
const free = ["Background removal", "Standard processing", "Limited usage"]
const pro = ["Higher usage", "Faster processing", "Batch processing", "Additional image tools"]
export default function PricingPage() { return <><SiteHeader /><main className="mx-auto max-w-[1100px] px-5 pb-20 pt-16 lg:px-8 lg:pt-24"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--muted)]">Pricing</p><h1 className="mt-4 font-display text-5xl font-bold tracking-[-.06em] sm:text-6xl">Simple pricing, when it&apos;s ready.</h1><p className="mt-5 text-lg leading-8 text-[var(--muted)]">Start with the core tool for free. Paid plans are being shaped around real usage and will be announced later.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2"><Plan title="Free" copy="For trying CutoutBG." features={free} /><Plan title="Pro" copy="For frequent image processing." features={pro} soon /></div></main><ProductFooter /></> }
function Plan({ title, copy, features, soon = false }: { title: string; copy: string; features: string[]; soon?: boolean }) { return <section className={`rounded-3xl border p-7 ${soon ? "border-[var(--deep)] bg-[var(--deep)] text-white" : "border-[var(--line)] bg-[var(--panel)]"}`}><div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-3xl font-bold">{title}</h2><p className={`mt-2 text-sm ${soon ? "text-white/70" : "text-[var(--muted)]"}`}>{copy}</p></div>{soon && <span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">Coming soon</span>}</div><ul className="mt-8 flex flex-col gap-4">{features.map((feature) => <li key={feature} className={`flex items-center gap-3 text-sm ${soon ? "text-white/85" : "text-[var(--foreground)]"}`}><Check className="size-4" aria-hidden="true" />{feature}</li>)}</ul><Link href={soon ? "/signup" : "/remove-background"} className={`mt-8 inline-flex items-center gap-2 text-sm font-bold ${soon ? "text-[var(--accent)]" : "text-[var(--foreground)]"}`}>{soon ? "Join the product preview" : "Try the core tool"}<ArrowRight className="size-4" aria-hidden="true" /></Link></section> }
